// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package scans_db

import (
	"database/sql"
	"time"
)

type Host struct {
	ID       int64
	ScansID  int64
	Address  string
	Status   string
	Hostname sql.NullString
	Os       sql.NullString
	Ports    sql.NullString
}

type Scan struct {
	ID        int64
	Type      string
	StartTime time.Time
	EndTime   sql.NullTime
}
